name: module3_task0
on:
  schedule:
    - cron: "0 0 * * *"
  push:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: git clone
        uses: actions/checkout@v3
      - name: Change directory and execute the Makefilee
        run: cd module3_task0 && make help
